# For more information: https://laravel.com/docs/sail
version: '3'
services:
    backend.reserve:
        build:
            context: ./backend/reserve
        image: ryokan2/backend.reserve
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-3000}:3000'
        volumes:
            - .:/app
            - backend.reserve.node_modules:/app/backend/reserve/node_modules
            - pnpm-store:/app/.pnpm-store
        command: "pnpm start:dev"
    bff.reserve:
        build:
            context: ./bff/reserve
        image: ryokan2/bff.reserve
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:3000'
        volumes:
            - .:/app
            - bff.reserve.node_modules:/app/bff/reserve/node_modules
            - pnpm-store:/app/.pnpm-store
        command: "pnpm dev"
    bff.system-admin:
        build:
            context: ./bff/system-admin
        image: ryokan2/bff.system-admin
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-81}:3000'
        volumes:
            - .:/app
            - bff.system-admin.node_modules:/app/bff/system-admin/node_modules
            - pnpm-store:/app/.pnpm-store
        command: "pnpm dev"
#         depends_on:
#             - mysql
#             - redis
#             - mailhog
#             - selenium
#     admin:
#         build:
#             context: ./admin/docker
#             args:
#                 WWWGROUP: '${WWWGROUP}'
#         image: ryokan/admin
#         extra_hosts:
#             - 'host.docker.internal:host-gateway'
#         ports:
#             - '${APP_ADMIN_PORT:-81}:80'
#             - '${VITE_ADMIN_PORT:-5174}:${VITE_PORT:-5173}'
#         environment:
#             WWWUSER: '${WWWUSER}'
#             LARAVEL_SAIL: 1
#             XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
#             XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
#         volumes:
#             - '.:/var/www/html'
#         networks:
#             - sail
#     mysql:
#         image: 'mysql/mysql-server:8.0'
#         ports:
#             - '${FORWARD_DB_PORT:-3306}:3306'
#         environment:
#             MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#             MYSQL_ROOT_HOST: "%"
#             MYSQL_DATABASE: '${DB_DATABASE}'
#             MYSQL_USER: '${DB_USERNAME}'
#             MYSQL_PASSWORD: '${DB_PASSWORD}'
#             MYSQL_ALLOW_EMPTY_PASSWORD: 1
#         volumes:
#             - 'sail-mysql:/var/lib/mysql'
#             - './admin/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
#         networks:
#             - sail
#         healthcheck:
#             test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
#             retries: 3
#             timeout: 5s
#     redis:
#         image: 'redis:alpine'
#         ports:
#             - '${FORWARD_REDIS_PORT:-6379}:6379'
#         volumes:
#             - 'sail-redis:/data'
#         networks:
#             - sail
#         healthcheck:
#             test: ["CMD", "redis-cli", "ping"]
#             retries: 3
#             timeout: 5s
#     mailhog:
#         image: 'mailhog/mailhog:latest'
#         ports:
#             - '${FORWARD_MAILHOG_PORT:-1025}:1025'
#             - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
#         networks:
#             - sail
#     selenium:
#         image: 'selenium/standalone-chrome'
#         volumes:
#             - '/dev/shm:/dev/shm'
#         networks:
#             - sail
volumes:
    bff.reserve.node_modules:
    bff.system-admin.node_modules:
    backend.reserve.node_modules:
    pnpm-store:
#     sail-mysql:
#         driver: local
#     sail-redis:
#         driver: local
